name: Deploy Staging environment

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gd-gcp-gridu-devops-t1-t2
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Connect to cluster
        run: gcloud container clusters get-credentials amatic-stage --region europe-west2 --project gd-gcp-gridu-devops-t1-t2

      - name: Apply Kubernetes Manifests for Stage environment
        run: |
          kubectl apply -f deploy/kubernetes/stage-secret.yaml
          kubectl apply -f deploy/kubernetes/complete-demo-stage.yaml